name: WeaselDailies
version: '${project.version}'
main: wassel.weaseldailies.WeaselDailies
api-version: '1.20'
commands:
  daily-reward:
    description: Rewards the player when a day has passed since the last time
    command: /<command>
    aliases:
      - dailyreward
      - daily
    permission: weaseldailies.dailyreward
    permission-message: You do not have permission to run this command
  force-daily-reward:
    description: Forces daily reward to a player bypassing the time checks
    command: /<command>
    aliases:
      - forcedailyreward
      - forcedaily
    permission: weaseldailies.forcedailyreward
    permission-message: You do not have permission to run this command
  reload:
    description: Reloads the plugin
    command: /<command>
    permission: weaseldailies.reload
    permission-message: You do not have permission to run this command
permissions:
  weaseldailies.daily-reward:
    description: Allows user to use the daily reward command
    default: op
  weaseldailies.force-daily-reward:
    description: Allows user to use the force daily reward command
    default: op
  weaseldailies.reload:
    description: Allows user to use the reload command
    default: op
  weaseldailies.*:
    description: Allows user to use all controls of Weasel dailies
    default: op
    children:
      weaseldailies.daily-reward: true
      weaseldailies.forcedailyreward: true
      weaseldailies.reload: true